#!/usr/bin/env bash
# Script to change localhost and facebook.com IP resolution
# - localhost resolves to 127.0.0.2
# - facebook.com resolves to 8.8.8.8

cp /etc/hosts ~/hosts.new
sed -i 's/127.0.0.1\slocalhost/127.0.0.2 localhost/g' ~/hosts.new
echo "8.8.8.8 facebook.com" >> ~/hosts.new
cp -f ~/hosts.new /etc/hosts 